//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntities : DbContext
    {
        public DbCvEntities()
            : base("name=DbCvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLADMIN> TBLADMINs { get; set; }
        public virtual DbSet<TBLDENEYIMLERIM> TBLDENEYIMLERIMs { get; set; }
        public virtual DbSet<TBLEGIITMLERIM> TBLEGIITMLERIMs { get; set; }
        public virtual DbSet<TBLHAKKINDA> TBLHAKKINDAs { get; set; }
        public virtual DbSet<TBLHOBILERIM> TBLHOBILERIMs { get; set; }
        public virtual DbSet<TBLILETISIM> TBLILETISIMs { get; set; }
        public virtual DbSet<TBLSERTIFIKALARIM> TBLSERTIFIKALARIMs { get; set; }
        public virtual DbSet<TBLYETENEKLERIM> TBLYETENEKLERIMs { get; set; }
    }
}
